import { MigrateUpArgs, MigrateDownArgs, sql } from '@payloadcms/db-vercel-postgres'

export async function up({ db, payload, req }: MigrateUpArgs): Promise<void> {
  await db.execute(sql`
   CREATE TYPE "public"."enum_pages_blocks_cta_background_color" AS ENUM('off-white', 'frozen-green', 'lavender', 'dark-teal', 'cerulean', 'orange');
  CREATE TYPE "public"."enum_pages_blocks_content_background_color" AS ENUM('off-white', 'frozen-green', 'lavender', 'dark-teal', 'cerulean', 'orange');
  CREATE TYPE "public"."enum_pages_blocks_media_block_background_color" AS ENUM('off-white', 'frozen-green', 'lavender', 'dark-teal', 'cerulean', 'orange');
  CREATE TYPE "public"."enum_pages_blocks_archive_background_color" AS ENUM('off-white', 'frozen-green', 'lavender', 'dark-teal', 'cerulean', 'orange');
  CREATE TYPE "public"."enum_pages_blocks_form_block_background_color" AS ENUM('off-white', 'frozen-green', 'lavender', 'dark-teal', 'cerulean', 'orange');
  CREATE TYPE "public"."enum_pages_blocks_feature_preview_background_color" AS ENUM('off-white', 'frozen-green', 'lavender', 'dark-teal', 'cerulean', 'orange');
  CREATE TYPE "public"."enum_pages_blocks_testimonials_background_color" AS ENUM('off-white', 'frozen-green', 'lavender', 'dark-teal', 'cerulean', 'orange');
  CREATE TYPE "public"."enum_pages_blocks_info_cards_background_color" AS ENUM('off-white', 'frozen-green', 'lavender', 'dark-teal', 'cerulean', 'orange');
  CREATE TYPE "public"."enum_pages_blocks_team_members_background_color" AS ENUM('off-white', 'frozen-green', 'lavender', 'dark-teal', 'cerulean', 'orange');
  CREATE TYPE "public"."enum_pages_blocks_accordion_info_background_color" AS ENUM('off-white', 'frozen-green', 'lavender', 'dark-teal', 'cerulean', 'orange');
  CREATE TYPE "public"."enum_pages_blocks_steps_background_color" AS ENUM('off-white', 'frozen-green', 'lavender', 'dark-teal', 'cerulean', 'orange');
  CREATE TYPE "public"."enum__pages_v_blocks_cta_background_color" AS ENUM('off-white', 'frozen-green', 'lavender', 'dark-teal', 'cerulean', 'orange');
  CREATE TYPE "public"."enum__pages_v_blocks_content_background_color" AS ENUM('off-white', 'frozen-green', 'lavender', 'dark-teal', 'cerulean', 'orange');
  CREATE TYPE "public"."enum__pages_v_blocks_media_block_background_color" AS ENUM('off-white', 'frozen-green', 'lavender', 'dark-teal', 'cerulean', 'orange');
  CREATE TYPE "public"."enum__pages_v_blocks_archive_background_color" AS ENUM('off-white', 'frozen-green', 'lavender', 'dark-teal', 'cerulean', 'orange');
  CREATE TYPE "public"."enum__pages_v_blocks_form_block_background_color" AS ENUM('off-white', 'frozen-green', 'lavender', 'dark-teal', 'cerulean', 'orange');
  CREATE TYPE "public"."enum__pages_v_blocks_feature_preview_background_color" AS ENUM('off-white', 'frozen-green', 'lavender', 'dark-teal', 'cerulean', 'orange');
  CREATE TYPE "public"."enum__pages_v_blocks_testimonials_background_color" AS ENUM('off-white', 'frozen-green', 'lavender', 'dark-teal', 'cerulean', 'orange');
  CREATE TYPE "public"."enum__pages_v_blocks_info_cards_background_color" AS ENUM('off-white', 'frozen-green', 'lavender', 'dark-teal', 'cerulean', 'orange');
  CREATE TYPE "public"."enum__pages_v_blocks_team_members_background_color" AS ENUM('off-white', 'frozen-green', 'lavender', 'dark-teal', 'cerulean', 'orange');
  CREATE TYPE "public"."enum__pages_v_blocks_accordion_info_background_color" AS ENUM('off-white', 'frozen-green', 'lavender', 'dark-teal', 'cerulean', 'orange');
  CREATE TYPE "public"."enum__pages_v_blocks_steps_background_color" AS ENUM('off-white', 'frozen-green', 'lavender', 'dark-teal', 'cerulean', 'orange');
  ALTER TYPE "public"."bg_color" RENAME TO "element_color";
  ALTER TYPE "public"."enum_pages_blocks_info_cards_info_cards_background_color" RENAME TO "enum_pages_blocks_info_cards_info_cards_element_color";
  ALTER TYPE "public"."enum_pages_blocks_team_members_people_background_color" RENAME TO "enum_pages_blocks_team_members_people_element_color";
  ALTER TYPE "public"."enum_pages_blocks_steps_steps_background_color" RENAME TO "enum_pages_blocks_steps_steps_element_color";
  ALTER TYPE "public"."enum__pages_v_blocks_info_cards_info_cards_background_color" RENAME TO "enum__pages_v_blocks_info_cards_info_cards_element_color";
  ALTER TYPE "public"."enum__pages_v_blocks_team_members_people_background_color" RENAME TO "enum__pages_v_blocks_team_members_people_element_color";
  ALTER TYPE "public"."enum__pages_v_blocks_steps_steps_background_color" RENAME TO "enum__pages_v_blocks_steps_steps_element_color";
  ALTER TABLE "pages_blocks_feature_preview_feature_previews" RENAME COLUMN "background_color" TO "element_color";
  ALTER TABLE "pages_blocks_info_cards_info_cards" RENAME COLUMN "background_color" TO "element_color";
  ALTER TABLE "pages_blocks_team_members_people" RENAME COLUMN "background_color" TO "element_color";
  ALTER TABLE "pages_blocks_steps_steps" RENAME COLUMN "background_color" TO "element_color";
  ALTER TABLE "_pages_v_blocks_feature_preview_feature_previews" RENAME COLUMN "background_color" TO "element_color";
  ALTER TABLE "_pages_v_blocks_info_cards_info_cards" RENAME COLUMN "background_color" TO "element_color";
  ALTER TABLE "_pages_v_blocks_team_members_people" RENAME COLUMN "background_color" TO "element_color";
  ALTER TABLE "_pages_v_blocks_steps_steps" RENAME COLUMN "background_color" TO "element_color";
  ALTER TABLE "pages_blocks_cta" ADD COLUMN "background_color" "enum_pages_blocks_cta_background_color";
  ALTER TABLE "pages_blocks_content" ADD COLUMN "background_color" "enum_pages_blocks_content_background_color";
  ALTER TABLE "pages_blocks_media_block" ADD COLUMN "background_color" "enum_pages_blocks_media_block_background_color";
  ALTER TABLE "pages_blocks_archive" ADD COLUMN "background_color" "enum_pages_blocks_archive_background_color";
  ALTER TABLE "pages_blocks_form_block" ADD COLUMN "background_color" "enum_pages_blocks_form_block_background_color";
  ALTER TABLE "pages_blocks_feature_preview" ADD COLUMN "background_color" "enum_pages_blocks_feature_preview_background_color";
  ALTER TABLE "pages_blocks_testimonials" ADD COLUMN "background_color" "enum_pages_blocks_testimonials_background_color";
  ALTER TABLE "pages_blocks_info_cards" ADD COLUMN "background_color" "enum_pages_blocks_info_cards_background_color";
  ALTER TABLE "pages_blocks_team_members" ADD COLUMN "background_color" "enum_pages_blocks_team_members_background_color";
  ALTER TABLE "pages_blocks_accordion_info" ADD COLUMN "background_color" "enum_pages_blocks_accordion_info_background_color";
  ALTER TABLE "pages_blocks_steps" ADD COLUMN "background_color" "enum_pages_blocks_steps_background_color";
  ALTER TABLE "_pages_v_blocks_cta" ADD COLUMN "background_color" "enum__pages_v_blocks_cta_background_color";
  ALTER TABLE "_pages_v_blocks_content" ADD COLUMN "background_color" "enum__pages_v_blocks_content_background_color";
  ALTER TABLE "_pages_v_blocks_media_block" ADD COLUMN "background_color" "enum__pages_v_blocks_media_block_background_color";
  ALTER TABLE "_pages_v_blocks_archive" ADD COLUMN "background_color" "enum__pages_v_blocks_archive_background_color";
  ALTER TABLE "_pages_v_blocks_form_block" ADD COLUMN "background_color" "enum__pages_v_blocks_form_block_background_color";
  ALTER TABLE "_pages_v_blocks_feature_preview" ADD COLUMN "background_color" "enum__pages_v_blocks_feature_preview_background_color";
  ALTER TABLE "_pages_v_blocks_testimonials" ADD COLUMN "background_color" "enum__pages_v_blocks_testimonials_background_color";
  ALTER TABLE "_pages_v_blocks_info_cards" ADD COLUMN "background_color" "enum__pages_v_blocks_info_cards_background_color";
  ALTER TABLE "_pages_v_blocks_team_members" ADD COLUMN "background_color" "enum__pages_v_blocks_team_members_background_color";
  ALTER TABLE "_pages_v_blocks_accordion_info" ADD COLUMN "background_color" "enum__pages_v_blocks_accordion_info_background_color";
  ALTER TABLE "_pages_v_blocks_steps" ADD COLUMN "background_color" "enum__pages_v_blocks_steps_background_color";`)
}

export async function down({ db, payload, req }: MigrateDownArgs): Promise<void> {
  await db.execute(sql`
   CREATE TYPE "public"."bg_color" AS ENUM('off-white', 'frozen-green', 'lavender', 'dark-teal', 'cerulean', 'orange');
  CREATE TYPE "public"."enum_pages_blocks_info_cards_info_cards_background_color" AS ENUM('off-white', 'frozen-green', 'lavender', 'dark-teal', 'cerulean', 'orange');
  CREATE TYPE "public"."enum_pages_blocks_team_members_people_background_color" AS ENUM('off-white', 'frozen-green', 'lavender', 'dark-teal', 'cerulean', 'orange');
  CREATE TYPE "public"."enum_pages_blocks_steps_steps_background_color" AS ENUM('off-white', 'frozen-green', 'lavender', 'dark-teal', 'cerulean', 'orange');
  CREATE TYPE "public"."enum__pages_v_blocks_info_cards_info_cards_background_color" AS ENUM('off-white', 'frozen-green', 'lavender', 'dark-teal', 'cerulean', 'orange');
  CREATE TYPE "public"."enum__pages_v_blocks_team_members_people_background_color" AS ENUM('off-white', 'frozen-green', 'lavender', 'dark-teal', 'cerulean', 'orange');
  CREATE TYPE "public"."enum__pages_v_blocks_steps_steps_background_color" AS ENUM('off-white', 'frozen-green', 'lavender', 'dark-teal', 'cerulean', 'orange');
  ALTER TABLE "pages_blocks_feature_preview_feature_previews" ADD COLUMN "background_color" "bg_color";
  ALTER TABLE "pages_blocks_info_cards_info_cards" ADD COLUMN "background_color" "enum_pages_blocks_info_cards_info_cards_background_color";
  ALTER TABLE "pages_blocks_team_members_people" ADD COLUMN "background_color" "enum_pages_blocks_team_members_people_background_color";
  ALTER TABLE "pages_blocks_steps_steps" ADD COLUMN "background_color" "enum_pages_blocks_steps_steps_background_color";
  ALTER TABLE "_pages_v_blocks_feature_preview_feature_previews" ADD COLUMN "background_color" "bg_color";
  ALTER TABLE "_pages_v_blocks_info_cards_info_cards" ADD COLUMN "background_color" "enum__pages_v_blocks_info_cards_info_cards_background_color";
  ALTER TABLE "_pages_v_blocks_team_members_people" ADD COLUMN "background_color" "enum__pages_v_blocks_team_members_people_background_color";
  ALTER TABLE "_pages_v_blocks_steps_steps" ADD COLUMN "background_color" "enum__pages_v_blocks_steps_steps_background_color";
  ALTER TABLE "pages_blocks_cta" DROP COLUMN "background_color";
  ALTER TABLE "pages_blocks_content" DROP COLUMN "background_color";
  ALTER TABLE "pages_blocks_media_block" DROP COLUMN "background_color";
  ALTER TABLE "pages_blocks_archive" DROP COLUMN "background_color";
  ALTER TABLE "pages_blocks_form_block" DROP COLUMN "background_color";
  ALTER TABLE "pages_blocks_feature_preview_feature_previews" DROP COLUMN "element_color";
  ALTER TABLE "pages_blocks_feature_preview" DROP COLUMN "background_color";
  ALTER TABLE "pages_blocks_testimonials" DROP COLUMN "background_color";
  ALTER TABLE "pages_blocks_info_cards_info_cards" DROP COLUMN "element_color";
  ALTER TABLE "pages_blocks_info_cards" DROP COLUMN "background_color";
  ALTER TABLE "pages_blocks_team_members_people" DROP COLUMN "element_color";
  ALTER TABLE "pages_blocks_team_members" DROP COLUMN "background_color";
  ALTER TABLE "pages_blocks_accordion_info" DROP COLUMN "background_color";
  ALTER TABLE "pages_blocks_steps_steps" DROP COLUMN "element_color";
  ALTER TABLE "pages_blocks_steps" DROP COLUMN "background_color";
  ALTER TABLE "_pages_v_blocks_cta" DROP COLUMN "background_color";
  ALTER TABLE "_pages_v_blocks_content" DROP COLUMN "background_color";
  ALTER TABLE "_pages_v_blocks_media_block" DROP COLUMN "background_color";
  ALTER TABLE "_pages_v_blocks_archive" DROP COLUMN "background_color";
  ALTER TABLE "_pages_v_blocks_form_block" DROP COLUMN "background_color";
  ALTER TABLE "_pages_v_blocks_feature_preview_feature_previews" DROP COLUMN "element_color";
  ALTER TABLE "_pages_v_blocks_feature_preview" DROP COLUMN "background_color";
  ALTER TABLE "_pages_v_blocks_testimonials" DROP COLUMN "background_color";
  ALTER TABLE "_pages_v_blocks_info_cards_info_cards" DROP COLUMN "element_color";
  ALTER TABLE "_pages_v_blocks_info_cards" DROP COLUMN "background_color";
  ALTER TABLE "_pages_v_blocks_team_members_people" DROP COLUMN "element_color";
  ALTER TABLE "_pages_v_blocks_team_members" DROP COLUMN "background_color";
  ALTER TABLE "_pages_v_blocks_accordion_info" DROP COLUMN "background_color";
  ALTER TABLE "_pages_v_blocks_steps_steps" DROP COLUMN "element_color";
  ALTER TABLE "_pages_v_blocks_steps" DROP COLUMN "background_color";
  DROP TYPE "public"."enum_pages_blocks_cta_background_color";
  DROP TYPE "public"."enum_pages_blocks_content_background_color";
  DROP TYPE "public"."enum_pages_blocks_media_block_background_color";
  DROP TYPE "public"."enum_pages_blocks_archive_background_color";
  DROP TYPE "public"."enum_pages_blocks_form_block_background_color";
  DROP TYPE "public"."element_color";
  DROP TYPE "public"."enum_pages_blocks_feature_preview_background_color";
  DROP TYPE "public"."enum_pages_blocks_testimonials_background_color";
  DROP TYPE "public"."enum_pages_blocks_info_cards_info_cards_element_color";
  DROP TYPE "public"."enum_pages_blocks_info_cards_background_color";
  DROP TYPE "public"."enum_pages_blocks_team_members_people_element_color";
  DROP TYPE "public"."enum_pages_blocks_team_members_background_color";
  DROP TYPE "public"."enum_pages_blocks_accordion_info_background_color";
  DROP TYPE "public"."enum_pages_blocks_steps_steps_element_color";
  DROP TYPE "public"."enum_pages_blocks_steps_background_color";
  DROP TYPE "public"."enum__pages_v_blocks_cta_background_color";
  DROP TYPE "public"."enum__pages_v_blocks_content_background_color";
  DROP TYPE "public"."enum__pages_v_blocks_media_block_background_color";
  DROP TYPE "public"."enum__pages_v_blocks_archive_background_color";
  DROP TYPE "public"."enum__pages_v_blocks_form_block_background_color";
  DROP TYPE "public"."enum__pages_v_blocks_feature_preview_background_color";
  DROP TYPE "public"."enum__pages_v_blocks_testimonials_background_color";
  DROP TYPE "public"."enum__pages_v_blocks_info_cards_info_cards_element_color";
  DROP TYPE "public"."enum__pages_v_blocks_info_cards_background_color";
  DROP TYPE "public"."enum__pages_v_blocks_team_members_people_element_color";
  DROP TYPE "public"."enum__pages_v_blocks_team_members_background_color";
  DROP TYPE "public"."enum__pages_v_blocks_accordion_info_background_color";
  DROP TYPE "public"."enum__pages_v_blocks_steps_steps_element_color";
  DROP TYPE "public"."enum__pages_v_blocks_steps_background_color";`)
}
